Cite: @Gutwin2010GoneBut, @Rekimoto1997PickDrop
Cotutor: Nombre del Co-tutor Académico
Csl: input/resources/csl/acm-sig-proceedings.csl
Department: Departamento tutor académico
Language: spanish
Month: Mes
Name: Nombre
Technology: Tecnología Específica
Title: Título
Tutor: Nombre del Tutor Académico
Year: Año
